spring:
    profiles:
        active:
        - dev

---
    spring:
        profiles: dev
        application:
            name: microconfig-config-client
---
    spring:
            profiles: beta            
            application:
                name: microconfig-config-client